[package]
name = "progressive_mcts"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fstrings = "0.2.3"
itertools = "0.10.1"
rand = "0.8.3"
rand_distr = "0.4.0"
rayon = "1.5.1"
